baseurl: "/"
languageCode: "zh-CN"
title: "QAQ LAND"
footnotereturnlinkcontents: "â†©"
enableRobotsTXT: true
copyright: |
  &copy;[QAQ](https://qaq.land) 1919 -- {Year} | [Github](https://github.com/qaqland) | [Gitlab](https://gitlab.com/qaqland)   
  Made with [Hugo](https://gohugo.io/).

relativeURLs: true
permalinks:
  /: /:year/:filename/
  night: /:section/:year/:yearday/

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "2022/about/"
      weight: 2
    - name: RSS
      url: "index.xml"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
